### ISSUE TITLE
Color use inconsistent between row and rack views

### ISSUE THREAD

**Issue by ijdod** [samilliken/openDCIM#1014]
I noticed the following difference between cabinet and row views. I'm not sure if this was deliberate, or just a small bug: In the cabinet view, the position column shows the color associated with the owner, unless there is a status color other than white, in which case the status color is shown. (for instance, the default cyan for Reserved).  

Looks like #807/#812, but this is in 4.5. 

In cabinet row view, it's only the owner color which is shown. Customer ABC is owner (red), status of the switch is Reserved (cyan)
![cabinet view](https://user-images.githubusercontent.com/33846784/36502081-17c1a870-1749-11e8-9b7f-f90a4b129a8c.jpg)
![row view](https://user-images.githubusercontent.com/33846784/36502082-17d94f2a-1749-11e8-8773-2602f1c43350.jpg)

**Comment by wilpig** [comment]
The row view is missing an !important flag on the reserved color to make it more important than department color.  someone else submitted a pull request that dealt with that and some other color stuff that I ignored because I didn’t really want a half depth device not marking the ownership on the other side of the rack
