### ISSUE TITLE
Can't create projects from Project Manager

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1151]
Somehow we broke this through a regression.

**Comment by wilpig** [comment]
I was able to recreate the problem and if any one of the date fields isn't set then the record isn't created.  it is not throwing a sql error to the log and debugging the sql is near impossible due to the use of prepared sql statements.

https://github.com/samilliken/openDCIM/blob/master/classes/Projects.class.php#L96

If you want me to fix it, i'm removing all that garbage and putting in the error tracking like we have everywhere else and creating the same makesafe/makedisplay functions that avoid the prepared sql black box voodoo

**Comment by samilliken** [comment]
This no longer appears to be an issue, as I have been able to create projects with nothing but a name.
