### ISSUE TITLE
Move child device to Storage General Room

### ISSUE THREAD

**Issue by AleSbTNS** [samilliken/openDCIM#1190]
Dear community, I can't move a child device (from a chassis) direct to the Genera Storage Room.
Do I commiting a mistake or the platform doens't support this movement?
From my POV, it's a issue, isn't it?

**Comment by nizzoball** [comment]
Been awhile since this issue was opened but the work around we did for this was create a large chassis and move it to the storage room, then when you decom a blade, move it to that chassis. Because of the way the child device sits in the database, its not possible or at least not practical to have a child device without s parent.
