### ISSUE TITLE
Add section to list devices assigned to cabinet but not a position (other than 0), similar to 0U devices.

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1268]
Valid point made on the mailing list - if you add a device to a cabinet but forget to list the position, it goes into the database with the only indicator being that you can search for it.   It would be a better experience if any assigned devices with unassigned positions could be added to the cabnavigator screen.

**Comment by timlegge** [comment]
Probably should be like the current copy device where it shows above the max U of the rack if you forget

**Comment by wilpig** [comment]
There is a very simple answer here.  Pick one:

1)  in the create device function Position=intval($this->Position)   <-- make sure there is a value, would default to 0
2) update the db schema to default the value to 0 for position so if a value isn't passed it will default to 0.

My preference is #1 since it will be consistent in the application

**Comment by wilpig** [comment]
https://github.com/samilliken/openDCIM/blob/master/classes/Device.class.php#L132  intval is already getting called in the makesafe.  https://github.com/samilliken/openDCIM/blob/master/classes/Device.class.php#L387  this here should never be nothing.  If devices on U0 aren't showing it's a bug.

**Comment by samilliken** [comment]
It's a bug in that devices on U0 don't show.   You can easily create a device without a position.   I'd almost rather check via JavaScript that if Size>0 and U==0 then don't pass go, but it will likely be easier to just list it with the 0U devices.
