### ISSUE TITLE
Clean up the Tags functions

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#522]
The old functions that reference fac_DeviceTags are still in assets.inc.php, and some pages still make calls to Device::GetTags, etc.  This is confusing and needs to be trimmed down to only what is being used going forward.

**Comment by wilpig** [comment]
Need more information because i'm not seeing where the confusion is coming from.  I see GetTags on the device class that gets the tags specific to that device and then I see a tags class that deals with actually managing the tags themselves.

[wilpig@hosting openDCIM]$ grep GetTags ./*
./assets.inc.php:	function GetTags() {
./assets.inc.php:	function GetTags() {
./cabinets.php:		$tags=$cab->GetTags();
./cabnavigator.php:    foreach ($obj->GetTags() as $tag)
./devices.php:			$tags=$dev->GetTags();
./report_asset_Excel.php:    $tag_list = $obj->GetTags();
./search_export.php:			$tags=implode(",", $dev->GetTags());
./search_export.php:					$ctags=implode(",", $child->GetTags());
[wilpig@hosting openDCIM]$ grep Tags:: ./*
./assets.inc.php:			$tags[]=Tags::FindName($row[0]);
./assets.inc.php:				$t=Tags::FindID($tag);
./assets.inc.php:					$t=Tags::CreateTag($tag);
./assets.inc.php:			$tags[]=Tags::FindName($tagid[0]);
./assets.inc.php:				$t=Tags::FindID($tag);
./assets.inc.php:					$t=Tags::CreateTag($tag);
./report_network_map.php:					$tList = Tags::FindAll();
./report_tags.php:	$tagsList=Tags::FindAll();

**Comment by samilliken** [comment]
I will look again and close the issue if I can't find a specific.  I
thought I had found a reference to the original table name in the database,
rather than the new one.

- Scott

On Wed, Jan 21, 2015 at 10:20 PM, Wilbur Longwisch <notifications@github.com

**Comment by samilliken** [comment]
This was a brain fart.  I was looking at fac_Tags and fac_DeviceTags thinking that one had replaced the other, which is not the case.  Closing.
