### ISSUE TITLE
More flexible power panel

### ISSUE THREAD

**Issue by puppetmaster886** [samilliken/openDCIM#613]
The is a possibility to name to each pole of the power panel,because we do not use number to name it we use well know name for each. Also there is any way to connect the power distribution to the power panel selecting individually each pole, because in our case we had resized the power of every cabinet over the time and because of the same cabinet have not consecutive poles.

**Comment by samilliken** [comment]
Show me a picture of what you are talking about, because every panel
enclosure that I've seen is numbered.  You might not use the numbers, but
the way that we have it defined in the software now is how every standard
I've ever seen refers to it.  That doesn't mean what you have is wrong, it
just means that you're going to have to explain it much better if you want
us to understand.

-- Scott

**Comment by puppetmaster886** [comment]
On the attached picture you can see our power panel (the standard panel on this part of the world). 
On this datacenter the power consumption per rack increased a lot since it was designed (10 years ago), but the space and cabinet number remain as same, then we had to add new circuits to the old cabinets. Then it was impossible to as that the circuit of the same cabinet continue been consecutive
![20150704_161702](https://cloud.githubusercontent.com/assets/8549792/8549762/ed9fce00-24a2-11e5-8a62-64b7a412be33.jpg)

**Comment by samilliken** [comment]
Ok, two things.

1.  That looks like a completely custom panel.  What you're asking us to do is add a feature to make it easier for you that will in turn make things more complex for 99% of the rest of the users that simply have numbered pole positions on their panels.
1b.  Even though your custom panel isn't labeled, there are a fixed number of pole positions.  Your breakers will either be single, double, or three pole breakers.  You need to figure out the total capacity in terms of breaker positions and then number them, just like taking a new data center floor and creating your own X-Y coordinate grid.

2.  I think there may still be a language disconnect because of your statement that you've added more circuits to existing cabinets, but they couldn't be consecutive numbers.  They don't need to be.  You would simply create a new CDU entry for each circuit.  Your CDU/Power Strip should only have one input to it.
