### ISSUE TITLE
Report: Cabinet List - wrong sort sequence

### ISSUE THREAD

**Issue by ds2k5** [samilliken/openDCIM#802]
Hello,
my Rack is 47 UE, and UE 1 is on Top.

![dcim_rack](https://cloud.githubusercontent.com/assets/11292286/17242201/2252233c-5576-11e6-81cc-b898bebfac46.png)

If i try the Report -> Cabinet List (Section: Operational Reports)
the Report show the wrong sort sequence. 47 is on Top and not the last.

![dcim_report](https://cloud.githubusercontent.com/assets/11292286/17242212/40991f62-5576-11e6-90b6-bc7f91c145d1.png)

Using: openDCIM 4.3 on Ubuntu 14.04 (64bit), php-5.5.9, MySQL-5.5.50, apache- 2.4.7-1

**Comment by samilliken** [comment]
This is not a bug, this is a configuration issue for your site.  There is an option to start at the top or bottom.  There is a global option under the Configuration tab (look for "U1 Position") and then each cabinet has the ability to override the global default.  Yours is apparently set to the top instead of bottom.
