### ISSUE TITLE
Wrong local ManufacturerID on pull

### ISSUE THREAD

**Issue by vobelic** [samilliken/openDCIM#816]
Steps to reproduce:
1. have a regular and working opendcim db (4.2+) with a few manufacturers pulled
2. check which manufacturer got auto-generated local ManufacturerID of 1 (must be
other than Generic)
3. try and pull some device templates for manufacturer from step 2.
4. check under which manufacturer did the device template end up, they
will end up under "Generic", i.e. ManufacturerID for those dev templates will be set to local ManufacturerID of "Generic" (which has GlobalID=1).

Sample:
> select * from fac_Manufacturer;
+----------------+----------------------+----------+--------------------+
| ManufacturerID | Name                 | GlobalID | SubscribeToUpdates |
+----------------+----------------------+----------+--------------------+
|              1 | HP                   |       26 |                  0 |
|              2 | Extreme Networks     |       46 |                  0 |
|              3 | Juniper              |       29 |                  0 |
|              4 | Generic              |        1 |                  0 |

In this case all dev templates for "HP" will be wrongly placed under Generic.

additional checks
5. try and pull device templates from _other_ manufacturers, different from the one in step 2. Those dev templates should get the proper ManufacturerID where they belong to.
6. try to manually remove the Generic manufacturer (GlobalID=1) from the fac_Manufacturer table
(without resyncing to the repo) and retry step 3.-4.; subsequently pulled dev templates from manufacturer from step 2 should now end up under proper manufacturer.
(note: previously pulled dev templates will
_remain_ under the wrong manufacturer even after the modification. Only pulls done afterwards will be placed properly.)

**Comment by wilpig** [comment]
Problem has been found.  The root cause was a double matching condition.  I started by setting up a clean environment and matched the following.

JS var arr_localmanf:
<img width="328" alt="screenshot 2016-08-29 08 03 51" src="https://cloud.githubusercontent.com/assets/1653882/18053634/17c514a2-6dc6-11e6-8e40-18922a6674fb.png">
DB Entries:
<img width="453" alt="screenshot 2016-08-29 08 04 00" src="https://cloud.githubusercontent.com/assets/1653882/18053640/1a3e446a-6dc6-11e6-94e7-13647737c619.png">


```
console.log("Pre Loop ManufacturerID: "+row.data("globaldev").ManufacturerID);
            // Find the local manufacturer id from the global value
            for(var key in arr_localmanf){
                if(arr_localmanf[key] === row.data("globaldev").ManufacturerID){
console.log("Setting ID to: "+key);
                    row.data("globaldev").ManufacturerID=key;
                }
            }
console.log("Post Loop ManufacturerID: "+row.data("globaldev").ManufacturerID);
```

I altered the javascript like above so I could watch the matching process happen.  Once I did that I saw this.

<img width="561" alt="screenshot 2016-08-29 08 49 25" src="https://cloud.githubusercontent.com/assets/1653882/18053589/db3d1020-6dc5-11e6-85d3-b64e49c173d3.png">

In the middle of the loop the match happened a second time.  So the first match set the ID correctly, as the loop continued it was matching against the changed value of row.data("globaldev").ManufacturerID so it managed to match again.  In theory this could happen several times over the course of one cycle putting the wrong ID in the loop repeatedly.
