### ISSUE TITLE
Report asset excel shows dummy entries

### ISSUE THREAD

**Issue by vobelic** [samilliken/openDCIM#821]
When exporting an asset report in excel (report_asset_Excel.php), there are non existing devices with "__EMPTY" under "Device" column in excel.

Additionaly, there's html tag <br> shown in the "Notes" column.

**Comment by AndHam89** [comment]
The "__EMPTY" entry enables quickly to see which rack places are empty and make some calculations on those. Therefore this placeholder was introduced.

**Comment by vinod-wagh** [comment]
Hi Team,

Facing the issue with asset report in excel (report_asset_Excel.php) it get stuck at 90% percent and doesn't export anything.

**Comment by AndHam89** [comment]
https://github.com/vinod-wagh, actually your question is off topic. You should create a separate incident for your issue since it is not related to the original question.

Did you check that your php process is allowed to use the resources it requires to generate the Excel file, maximum allowed amount of memory and/or maximum length of computation? The library which is used to generate the Excel file uses a lot of resources. So you should monitor on the web server the resource usage while the Excel is generated. The required resources grows with the size of you objects managed by openDCIM.

Another possibility you may not see an Excel report is that you may have been able to create a loop in your data structure. I have seen this when an update of an older version was done and some fields had been misused. Most likely, this is not your problem if you have seen an Excel report before.
