### ISSUE TITLE
No [Buld Import] and [Logout] in Menu on the left pane?

### ISSUE THREAD

**Issue by cnguyen-home** [samilliken/openDCIM#850]
Hello, 
For evaluatation and see how the product work, I've followed the tutorial and setup OpenDCIM locally in an VM (CentOS7). The downloaded version is 4.3.1 but the screen menu is not the same as the screen show in the Wiki, especially in my local VM/OpenDCIM on the left I don't see [Bult Import] and [Logout] in the Menu options ?
Is the installation procedure correct or do I miss something? May be these options are not available yet in version 4.3.1 ?!?
Thks&BstRgds
Charles

**Comment by samilliken** [comment]
Please see the FAQ for how to obtain support.  Github issues is not for asking questions on how to use the software, it's for tracking development issues.

These questions have been answered on the mailing list many times.  Bulk Import requires that you give yourself permission to use it.  Logout only appears when you are using LDAP, because in all other circumstances, openDCIM is not handling your session.
