### ISSUE TITLE
XML Validation File needs updating

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#937]
Apparently the XML import/export depends on opeDCIMdevicetemplate.xsd to validate the fields against.  Since that has changed, it needs to be updated.

**Comment by wilpig** [comment]
Let's just do away with the xml entirely and make a modified json template based something

On Jul 24, 2017 6:50 AM, Scott Milliken <notifications@github.com> wrote:

Apparently the XML import/export depends on opeDCIMdevicetemplate.xsd to validate the fields against. Since that has changed, it needs to be updated.

**Comment by wilpig** [comment]
I’ll try to make time this week to revamp that.  What I’m thinking is take the template model object, then append on the front and rear image as uuencoded strings in appropriate fields, then json encode the object like we do for the api, etc.  Finally write that out to a plain text file, or if we want to be fancy gzip that to make it smaller.  The import side would be unzip -> make new template object -> iterate over the imported string -> save the object to the db -> convert the images to the format of <new templateid>_manufacturer_model -> update the object once more for the new file names

**Comment by samilliken** [comment]
We're on the same page.  I planned on plagiarizing as much of our
repository API code as possible, only writing to a file instead of a stream.

Scott
