### ISSUE TITLE
Notes on device ports aren't being copied from Template to devices

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#960]

**Comment by samilliken** [comment]
Also when making a connection from devA to devB, copy the notes already in place on devA over to the same port on devB.

**Comment by wilpig** [comment]
<img width="1105" alt="screenshot 2017-10-02 07 45 36" src="https://user-images.githubusercontent.com/1653882/31077848-b85b0994-a745-11e7-9136-48605c7b8a81.png">

So the issue is that the device template uses the PortNotes field for the templates, when we make the ports for the device we loop over the model and populate the same fields.  For the device connections we are using the Notes field and not PortNotes so in reality we are populating the fields from the template but you can't see them.
