### ISSUE TITLE
v4.5 redirect consideration

### ISSUE THREAD

**Issue by ikcilabd** [samilliken/openDCIM#965]
In misc.inc.php, the redirect function uses the $_SERVER['SERVER_NAME'] value instead of $_SERVER['HTTP_HOST'] like in previous versions.  Not sure if this was changed for a reason but had some issues w/ it stripping out ports from the url(in dev implementations), may cause some headaches depending on the url being used or if dns issues arise.

**Comment by samilliken** [comment]
If I recall correctly, it was changed to work better with NGINX.

Scott

**Comment by ikcilabd** [comment]
ok, guess I can put in a check on $_SERVER['SERVER_PORT'], e.g.:
```
	if ($_SERVER['SERVER_PORT'] != 80 || $_SERVER['SERVER_PORT'] != 443){
		$base_url = $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'];
	} else {
		$base_url = $_SERVER['SERVER_NAME'];
	}

	if(array_key_exists('HTTPS', $_SERVER) && $_SERVER["HTTPS"]=='on') {
		$url = "https://".$base_url.$target;
	} else {
		$url = "http://".@$base_url.$target;
	}
```

**Comment by lucamaro** [comment]
We have the same problem too, see #963. We use dcim in docker container in production and this change broke functionalities from upgrade to insert/delete devices, at least.

**Comment by wilpig** [comment]
This kind of hodge podge fix is not going to happen.  What I will do to get around this problem is the right way to handle it and put in an optional redirect url base into the configuration page and if that is set then it will skip the detection of the environment and will just use whatever URL is defined.  If not defined then the existing function will handle it.

**Comment by ThomasADavis** [comment]
I did this, because what was happening is the system was sending back the host it was on, not the URL it was referenced from, making it impossible to use behind a proxy (we proxy *everything*, so we can log it all)

**Comment by lucamaro** [comment]
All you need when you are behind a reverse proxy is to set apache ProxyPassReverse or nginx proxy_pass/proxy_redirect directives. That's the standard way those reverse proxy manipulate Location header when sending response to the client. But the Location sent from dcim must be the expected one (HTTP_HOST or SERVER_NAME +  SERVER_PORT), otherwise it does not work.

No other configuration is really needed other than for sending links through other transports (eg. email) or something like that.

**Comment by ThomasADavis** [comment]
Tried that.  Did not work.

The Hostname was being embeded into pages it self.

**Comment by duhow** [comment]
> `HTTP_HOST` is the target host sent by the client. It can be manipulated freely by the user. It's no problem to send a request to your site asking for a `HTTP_HOST` value of www.google.com.
`SERVER_NAME` comes from the server's VirtualHost definition and is therefore considered more reliable. 

Having it as `SERVER_NAME` + `SERVER_PORT` seems good  to me. I'll make a patch later for this. :slightly_smiling_face:
