### ISSUE TITLE
Updating port connections - notes not updated

### ISSUE THREAD

**Issue by jmcbxl** [samilliken/openDCIM#981]
Let's say we have got server1, server2, server3.

First, I connect server1-port1 to server2-port2. I add a note : cable12 and media type.
This automatically updates the server2-port2 with connection to server1-port1 and the same note and media type. This is quite logic as those are the 2 ends of the same cable.

Now, on server1-port1, I update the connection and I set it to server3-port3 and I change also the note to cable13. Logically, this automatically updates server3-port3 with the connection to server1-port1 and the same note and media type.

We should expect that information on server2-port2 gets fully cleared, since it is not connected anymore. But, in fact, only the connection to server1-port1 gets cleared, but the note (cable12) and media type are still present.
I have got the same problem if I simply clear the connection on server1-port1 (instead of updating it) : It remains configured on the other end...

I guess, the other end should also be fully cleared.

**Comment by wilpig** [comment]
Why would we clear the note or the media type?  Is the port going to magically change from fiber to copper just because you pulled the cable?  Likewise maybe there is something in the note that you could use as a reference later.

We clear the connection because it is gone the rest of the information is just meta data and we don't clear it for that reason.

**Comment by jmcbxl** [comment]
Why then insert a new note a the other side… Either the note concerns the port (and then, there is no reason to update it at both side at the same time), or the note concerns the link between them and, the, we should keep consistency: add them together, remove them together or update them together.
The current implementation (adding at the other side, but not updating it, is something quite inconsistent..)

If this is not possible, better then to NOT add the note at the other side AND think about a note related to the link itself (where we could put cable ID, length, …)

De : Wilbur Longwisch [mailto:notifications@github.com]
Envoyé : mardi 14 novembre 2017 13:49
À : samilliken/openDCIM <openDCIM@noreply.github.com>
Cc : COUNET Jean-Marc <jean-marc.counet@uclouvain.be>; Author <author@noreply.github.com>
Objet : Re: [samilliken/openDCIM] Updating port connections - notes not updated (#981)


Why would we clear the note or the media type? Is the port going to magically change from fiber to copper just because you pulled the cable? Likewise maybe there is something in the note that you could use as a reference later.

We clear the connection because it is gone the rest of the information is just meta data and we don't clear it for that reason.

**Comment by wilpig** [comment]
It is possible, I just said i'm not doing it and I gave you the reasons why it was done this way.  The current implementation is consistent in the fact that we add data and don't accidentally remove it.  Just because you use the notes field for something specific to the cable doesn't mean everyone does.
