### ISSUE TITLE
Upload directory 'pictures' is not writable

### ISSUE THREAD

**Issue by LukasMaximusAurelius** [samilliken/openDCIM#982]
We have an opendcim instance behind apache basic auth, and for the most part our install is working.
One of the problems we have is our instance does not have connectivity to the internet, therefore any imports of templates/pictures have to be downloaded from the internet manually, scp'd into our sandboxed environment, and then imported manually through the GUI.

We are running on RedHat 7.2
opendcim version 4.3.1

Although all permissions are set correctly, when navigating through the GUI to:
Template Management > Device Image Management > Device Pictures > Select Image > Open
We get the message "Upload directory 'pictures' is not writable"

Apache is showing a 200 response in the access log from the PUT request, which suggests the image is being uploaded. No errors exist in our error_log. The browser/GUI states otherwise, and no image is put in the 'pictures' directory which corresponds with the error we get on screen.

Can anyone offer any assistance/ideas, please?

**Comment by wilpig** [comment]
Selinux is not your friend and use the mailing list for questions.  Upgrade to 4.5 and you can import templates from the repo as long as your desktop has internet connectivity, but your permissions problem will still persist because that is OS related and not opendcim.   http://<your opendcim install>/rightscheck.php
